baseURL = "https://www.gbdkjs.com/"
languageCode = "en-gb"
title = "GBDK.js"
theme = "gbdkjs"

[[menu.main]]
    name = "About"
    title = "About"
    url = "/about/"

[[menu.main]]
    name = "Docs"
    title = "Docs"
    url = "/docs/"

[[menu.main]]
    name = "Download"
    title = "Download"
    url = "/docs/installation/"

[[menu.main]]
    name = "GitHub"
    title = "GitHub"
    url = "https://github.com/gbdkjs"
